apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: travel-agency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: travel/config-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8888
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: travel-agency
spec:
  selector:
    app: config-server
  ports:
    - port: 8888
      targetPort: 8888
