# Shared configuration for all microservices
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Security configurations (Keycloak)
spring.security.oauth2.client.registration.keycloak.client-id=travel-backend
spring.security.oauth2.client.registration.keycloak.client-secret=UD4BhZsGWX8AVOS41CqL8FwaSGGsZYjI
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code

spring.security.oauth2.client.provider.keycloak.issuer-uri=https://auth.trebolapp.cl/realms/travel-realm
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://auth.trebolapp.cl/realms/travel-realm
