# Shared configuration for all microservices
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# oauth2ResourceServer deshabilitado temporalmente — se reactivará
# cuando todos los servicios funcionen correctamente.
# spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:9090/realms/travel-realm/protocol/openid-connect/certs
